{"uid":"9083913c40598e64","name":"test_setup","fullName":"tests.integration.test_smoke#test_setup","historyId":"d623373ae070a62cab8e4b2f9dd522ae","time":{"start":1728437122960,"stop":1728437691988,"duration":569028},"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: postgresql/0","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/tests/integration/test_smoke.py\", line 36, in test_setup\n    await ops_test.model.wait_for_idle(\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 2964, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 2870, in _raise_for_status\n    raise error_type(\"{}{} in {}: {}\".format(\njuju.errors.JujuUnitError: Unit in error: postgresql/0","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"tmp_path_factory","time":{"start":1728437122783,"stop":1728437122783,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1728437122783,"stop":1728437122959,"duration":176},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1728437122783,"stop":1728437122783,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1728437122959,"stop":1728437122959,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"juju.errors.JujuUnitError: Unit in error: postgresql/0","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 880, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/tests/integration/test_smoke.py\", line 36, in test_setup\n    await ops_test.model.wait_for_idle(\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 2964, in wait_for_idle\n    _raise_for_status(errors, \"error\")\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.10/site-packages/juju/model.py\", line 2870, in _raise_for_status\n    raise error_type(\"{}{} in {}: {}\".format(\njuju.errors.JujuUnitError: Unit in error: postgresql/0","steps":[],"attachments":[{"uid":"c10b4dafd6534c2a","name":"log","source":"c10b4dafd6534c2a.txt","type":"text/plain","size":52361}],"parameters":[],"stepsCount":0,"shouldDisplayMessage":true,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1728437692026,"stop":1728437692026,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1728437692027,"stop":1728437693563,"duration":1536},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1728437693564,"stop":1728437693564,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1728437693564,"stop":1728437693564,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1728437693564,"stop":1728437693565,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"shouldDisplayMessage":false,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"group(1)"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_smoke"},{"name":"host","value":"fv-az568-841"},{"name":"thread","value":"15780-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_smoke"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"282a0eefffdfe263","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":14,"skipped":0,"passed":83,"unknown":7,"total":104},"items":[{"uid":"9e73156a6d18a08","reportUrl":"../1630//#testresult/9e73156a6d18a08","status":"passed","time":{"start":1728350585796,"stop":1728351735648,"duration":1149852}},{"uid":"e4679b4839929355","reportUrl":"../1625//#testresult/e4679b4839929355","status":"passed","time":{"start":1728264222630,"stop":1728265441311,"duration":1218681}},{"uid":"b5f3aa8ee1586ab7","reportUrl":"../1623//#testresult/b5f3aa8ee1586ab7","status":"passed","time":{"start":1728177817870,"stop":1728178965248,"duration":1147378}},{"uid":"4f20409b509c03f0","reportUrl":"../1621//#testresult/4f20409b509c03f0","status":"passed","time":{"start":1728091377339,"stop":1728092526773,"duration":1149434}},{"uid":"4f5250c338c07611","reportUrl":"../1618//#testresult/4f5250c338c07611","status":"passed","time":{"start":1728004970389,"stop":1728006135498,"duration":1165109}},{"uid":"6a556f556beb3ca6","reportUrl":"../1611//#testresult/6a556f556beb3ca6","status":"passed","time":{"start":1727918603030,"stop":1727919742643,"duration":1139613}},{"uid":"45223a0121bf13a1","reportUrl":"../1604//#testresult/45223a0121bf13a1","status":"passed","time":{"start":1727832168902,"stop":1727833251426,"duration":1082524}},{"uid":"efb16ab7cecb9970","reportUrl":"../1602//#testresult/efb16ab7cecb9970","status":"passed","time":{"start":1727745962931,"stop":1727747116673,"duration":1153742}},{"uid":"d9ac7f5cb41957a7","reportUrl":"../1598//#testresult/d9ac7f5cb41957a7","status":"passed","time":{"start":1727659385595,"stop":1727660488838,"duration":1103243}},{"uid":"f88c07a0fc6a8e94","reportUrl":"../1597//#testresult/f88c07a0fc6a8e94","status":"passed","time":{"start":1727572981577,"stop":1727574074804,"duration":1093227}},{"uid":"17173584a741a2f","reportUrl":"../1595//#testresult/17173584a741a2f","status":"passed","time":{"start":1727486614298,"stop":1727487791260,"duration":1176962}},{"uid":"62a37c6f23d352c","reportUrl":"../1579//#testresult/62a37c6f23d352c","status":"passed","time":{"start":1727400164957,"stop":1727401252730,"duration":1087773}},{"uid":"17a0c719156ae3c9","reportUrl":"../1570//#testresult/17a0c719156ae3c9","status":"passed","time":{"start":1727313771531,"stop":1727314851757,"duration":1080226}},{"uid":"56c5124acd3f481","reportUrl":"../1564//#testresult/56c5124acd3f481","status":"passed","time":{"start":1727227379447,"stop":1727228510912,"duration":1131465}},{"uid":"9cb2d108d748e3dd","reportUrl":"../1562//#testresult/9cb2d108d748e3dd","status":"passed","time":{"start":1727141013056,"stop":1727142124783,"duration":1111727}},{"uid":"452c8f95e82b6c56","reportUrl":"../1561//#testresult/452c8f95e82b6c56","status":"passed","time":{"start":1727054563830,"stop":1727055684117,"duration":1120287}},{"uid":"8c813e78edbc7108","reportUrl":"../1558//#testresult/8c813e78edbc7108","status":"passed","time":{"start":1726968193107,"stop":1726969285250,"duration":1092143}},{"uid":"2559ce482543623b","reportUrl":"../1556//#testresult/2559ce482543623b","status":"passed","time":{"start":1726881786120,"stop":1726882906501,"duration":1120381}},{"uid":"b4863a752552c445","reportUrl":"../1553//#testresult/b4863a752552c445","status":"passed","time":{"start":1726795356588,"stop":1726796467651,"duration":1111063}},{"uid":"33d85a026bafad37","reportUrl":"../1551//#testresult/33d85a026bafad37","status":"passed","time":{"start":1726708967102,"stop":1726710041386,"duration":1074284}}]},"tags":["asyncio","abort_on_fail","group(1)"]},"source":"9083913c40598e64.json","parameterValues":[]}