{"uid":"c1f06f76687e731","name":"test_setup","fullName":"tests.integration.test_smoke#test_setup","historyId":"d623373ae070a62cab8e4b2f9dd522ae","time":{"start":1752629061634,"stop":1752629062938,"duration":1304},"status":"broken","statusMessage":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 344, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 246, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 900, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 263, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 178, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1670, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 156, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/tests/integration/test_smoke.py\", line 34, in test_setup\n    await ops_test.model.deploy(\"./releases/latest/postgresql-bundle.yaml\")\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/model/__init__.py\", line 1914, in deploy\n    await handler.execute_plan()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/bundle.py\", line 453, in execute_plan\n    await self._resolve_charms()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/bundle.py\", line 436, in _resolve_charms\n    charm_url, charm_origin = await self.model._resolve_charm(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/model/__init__.py\", line 2078, in _resolve_charm\n    resp = await charms_facade.ResolveCharms(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/facade.py\", line 482, in wrapper\n    reply = await f(*args, **kwargs)\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/_client6.py\", line 276, in ResolveCharms\n    reply = await self.rpc(msg)\n            ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/facade.py\", line 680, in rpc\n    result = await self.connection.rpc(msg, encoder=TypeEncoder)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/connection.py\", line 597, in rpc\n    raise errors.JujuAPIError(result)\njuju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"event_loop","time":{"start":1752629061506,"stop":1752629061507,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test","time":{"start":1752629061507,"stop":1752629061633,"duration":126},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1752629061507,"stop":1752629061507,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1752629061633,"stop":1752629061633,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"broken","statusMessage":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","statusTrace":"Traceback (most recent call last):\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 344, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 246, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 900, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 263, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 178, in pytest_runtest_call\n    item.runtest()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1670, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 156, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/tests/integration/test_smoke.py\", line 34, in test_setup\n    await ops_test.model.deploy(\"./releases/latest/postgresql-bundle.yaml\")\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/model/__init__.py\", line 1914, in deploy\n    await handler.execute_plan()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/bundle.py\", line 453, in execute_plan\n    await self._resolve_charms()\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/bundle.py\", line 436, in _resolve_charms\n    charm_url, charm_origin = await self.model._resolve_charm(\n                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/model/__init__.py\", line 2078, in _resolve_charm\n    resp = await charms_facade.ResolveCharms(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/facade.py\", line 482, in wrapper\n    reply = await f(*args, **kwargs)\n            ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/_client6.py\", line 276, in ResolveCharms\n    reply = await self.rpc(msg)\n            ^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/facade.py\", line 680, in rpc\n    result = await self.connection.rpc(msg, encoder=TypeEncoder)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/postgresql-bundle/postgresql-bundle/.tox/integration/lib/python3.12/site-packages/juju/client/connection.py\", line 597, in rpc\n    raise errors.JujuAPIError(result)\njuju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","steps":[],"attachments":[{"uid":"217d8dd577433481","name":"log","source":"217d8dd577433481.txt","type":"text/plain","size":1100}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1752629062960,"stop":1752629062960,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1752629062961,"stop":1752629063206,"duration":245},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1752629063206,"stop":1752629063207,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1752629063207,"stop":1752629063207,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1752629063207,"stop":1752629063207,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_smoke"},{"name":"host","value":"pkrvmq0rgcvqdmg"},{"name":"thread","value":"11661-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_smoke"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"5fa05a21ea025137","status":"unknown","time":{}}],"categories":[{"name":"Test defects","matchedStatuses":[]}],"history":{"statistic":{"failed":0,"broken":48,"skipped":0,"passed":313,"unknown":17,"total":378},"items":[{"uid":"67684e597b71835a","reportUrl":"../2244//#testresult/67684e597b71835a","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752542625932,"stop":1752542627568,"duration":1636}},{"uid":"b40d8e248c89ddc5","reportUrl":"../2243//#testresult/b40d8e248c89ddc5","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752456223337,"stop":1752456225568,"duration":2231}},{"uid":"5c59bf7928bf0bad","reportUrl":"../2242//#testresult/5c59bf7928bf0bad","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752369830044,"stop":1752369830978,"duration":934}},{"uid":"8b9dfa3efe22d275","reportUrl":"../2241//#testresult/8b9dfa3efe22d275","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752283457800,"stop":1752283460359,"duration":2559}},{"uid":"57ba445cfc1dc758","reportUrl":"../2240//#testresult/57ba445cfc1dc758","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752197024426,"stop":1752197024974,"duration":548}},{"uid":"e86c1df6ac30e0c6","reportUrl":"../2239//#testresult/e86c1df6ac30e0c6","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752110659260,"stop":1752110660858,"duration":1598}},{"uid":"f9bfbcbb51bd2f58","reportUrl":"../2238//#testresult/f9bfbcbb51bd2f58","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1752024209838,"stop":1752024211602,"duration":1764}},{"uid":"98395d42ac0c276c","reportUrl":"../2236//#testresult/98395d42ac0c276c","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751937852715,"stop":1751937854223,"duration":1508}},{"uid":"8e3b9e7aa2a82163","reportUrl":"../2235//#testresult/8e3b9e7aa2a82163","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751851418824,"stop":1751851419911,"duration":1087}},{"uid":"e4665dae878b542d","reportUrl":"../2234//#testresult/e4665dae878b542d","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751765036248,"stop":1751765037490,"duration":1242}},{"uid":"47a57d8365da5503","reportUrl":"../2233//#testresult/47a57d8365da5503","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751678582769,"stop":1751678584652,"duration":1883}},{"uid":"7d46085ddceaa489","reportUrl":"../2232//#testresult/7d46085ddceaa489","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751592198297,"stop":1751592198838,"duration":541}},{"uid":"672752696a6874b3","reportUrl":"../2231//#testresult/672752696a6874b3","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751505805731,"stop":1751505806290,"duration":559}},{"uid":"4a12e34107c28691","reportUrl":"../2230//#testresult/4a12e34107c28691","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751419442460,"stop":1751419443798,"duration":1338}},{"uid":"daf04cef4d49b36d","reportUrl":"../2228//#testresult/daf04cef4d49b36d","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751333062094,"stop":1751333064283,"duration":2189}},{"uid":"3ca1041131ee72b","reportUrl":"../2227//#testresult/3ca1041131ee72b","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751246610026,"stop":1751246611954,"duration":1928}},{"uid":"1c324d93ef1eef9f","reportUrl":"../2226//#testresult/1c324d93ef1eef9f","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751160235531,"stop":1751160236226,"duration":695}},{"uid":"71bca92abc99b941","reportUrl":"../2225//#testresult/71bca92abc99b941","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1751073799316,"stop":1751073800488,"duration":1172}},{"uid":"61383f40409bd2d5","reportUrl":"../2224//#testresult/61383f40409bd2d5","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1750987401845,"stop":1750987404835,"duration":2990}},{"uid":"c5730ed11281ccba","reportUrl":"../2209//#testresult/c5730ed11281ccba","status":"broken","statusDetails":"juju.errors.JujuAPIError: transforming slice at index 0: cannot parse name and/or revision in URL \"\": name \"\" not valid","time":{"start":1750901012447,"stop":1750901013047,"duration":600}}]},"tags":["asyncio","abort_on_fail"]},"source":"c1f06f76687e731.json","parameterValues":[]}